name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
    steps:
      - uses: actions/checkout@v2
      - name: Pip Install
        run: >
          pip install -e . &&
          pip install pyopenssl[security] &&
          pip install -r canine/test/requirements.txt &&
          pip install coveralls
      - name: Run Tests
        run: python -m unittest discover canine/test
